FROM node:18-alpine

WORKDIR /app/backend

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --production

# Copy application files
COPY . .

# Expose port
EXPOSE 5001

# Start the application
CMD ["npm", "start"]
